all:
	strfile misc
	strfile signatures
	strfile lisp
	ln -s misc misc.u8
	ln -s signatures signatures.u8
	ln -s lips lisp.u8

clean:
	rm -f misc.dat misc.u8 signatures.dat signatures.u8 lisp.dat lisp.u8
